[theme]
base = "dark"
primaryColor = "#e9c176"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1b3022"
textColor = "#e5e2e1"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
